### ISSUE TITLE
Problem when installing in linux and mac

### ISSUE THREAD

**Issue by patrickelectric** [blinemedical/setup-gstreamer#180]
Executing subproject gst-libav:FFmpeg:win-nasm

win-nasm| Project name: win-nasm
win-nasm| Project version: 2.15.04

subprojects/win-nasm/meson.build:6:2: ERROR: Problem encountered: Can only download nasm for Windows, sorry

A full log can be found at /home/runner/work/mini-egui/mini-egui/gstreamer_src/builddir/meson-logs/meson-log.txt
Error: The process '/usr/local/bin/meson' failed with exit code 1

**Comment by jasonashton** [comment]
+1 Also having this issue

**Comment by btgoodwin** [comment]
I apologize for the long delay in responding.  Can you provide more information about your setup, @patrickelectric?  For example:

1. What version of this action are you targeting in your runner configuration?
2. What version of gstreamer are you trying to install in the runner?
3. What system and version is the runner?
4. Is this one of GitHub's runners or your own?

^^ Same questions for you as well, @jasonashton.

**Comment by btgoodwin** [comment]
No updates in months, so I'm closing this.  If either of you are still having issues, please reply and we can re-open.

I recently tried building from source in linux and ran into the win-nasm message.  The only way I could get around it was to manually disable the dependent gstreamer package, which I have not integrated such a change here because that's a bug in the upstream gstreamer source build tree AFAIK.  There are many meson build targets that seem to be missing necessary platform checks, etc. to automatically disable themselves.

As for how this is impacting mac installations, I don't see how this could be.  That part of the code for this action installs from pre-built packages posted by GStreamer itself.
